import React, { useState } from 'react';
import { Copy, Check, Download, ExternalLink, RefreshCw, FileCode, CheckCircle2, AlertCircle } from 'lucide-react';

export const RobotsSitemapTool: React.FC = () => {
  const [activeTab, setActiveTab] = useState<'robots' | 'sitemap'>('robots');
  const [copied, setCopied] = useState(false);

  // Robots.txt generator state
  const [cmsPreset, setCmsPreset] = useState<'wordpress' | 'shopify' | 'nextjs' | 'custom'>('wordpress');
  const [siteDomain, setSiteDomain] = useState('https://example.com');
  const [allowPublic, setAllowPublic] = useState(true);
  const [disallowAdmin, setDisallowAdmin] = useState(true);
  const [disallowSearch, setDisallowSearch] = useState(true);
  const [crawlDelay, setCrawlDelay] = useState('0');
  const [customRules, setCustomRules] = useState('Disallow: /checkout/\nDisallow: /cart/\nDisallow: /*?preview=*');

  // Sitemap generator state
  const [urls, setUrls] = useState([
    { path: '/', priority: '1.0', changefreq: 'daily', lastmod: '2026-03-27' },
    { path: '/services', priority: '0.8', changefreq: 'weekly', lastmod: '2026-03-25' },
    { path: '/blog', priority: '0.8', changefreq: 'daily', lastmod: '2026-03-26' },
    { path: '/case-studies', priority: '0.7', changefreq: 'weekly', lastmod: '2026-03-20' },
    { path: '/about', priority: '0.6', changefreq: 'monthly', lastmod: '2026-03-15' },
    { path: '/contact', priority: '0.5', changefreq: 'monthly', lastmod: '2026-03-10' },
  ]);

  const [newUrlPath, setNewUrlPath] = useState('');
  const [newUrlPriority, setNewUrlPriority] = useState('0.7');

  const generateRobotsTxt = () => {
    let content = `# robots.txt generated by SEO Ops & Automation Hub\n# Site: ${siteDomain}\n\nUser-agent: *\n`;

    if (!allowPublic) {
      return content + 'Disallow: /\n';
    }

    if (disallowAdmin) {
      if (cmsPreset === 'wordpress') {
        content += 'Disallow: /wp-admin/\nAllow: /wp-admin/admin-ajax.php\n';
      } else if (cmsPreset === 'shopify') {
        content += 'Disallow: /admin/\nDisallow: /orders/\n';
      } else {
        content += 'Disallow: /admin/\nDisallow: /api/internal/\n';
      }
    }

    if (disallowSearch) {
      content += 'Disallow: /search\nDisallow: /*?s=*\n';
    }

    if (customRules.trim()) {
      content += customRules.trim() + '\n';
    }

    if (crawlDelay !== '0') {
      content += `Crawl-delay: ${crawlDelay}\n`;
    }

    content += `\n# Sitemaps resource submission (Task #19 & #44)\nSitemap: ${siteDomain.replace(/\/$/, '')}/sitemap.xml\n`;

    return content;
  };

  const generateSitemapXml = () => {
    const formattedUrls = urls
      .map(
        (u) => `  <url>
    <loc>${siteDomain.replace(/\/$/, '')}${u.path.startsWith('/') ? u.path : '/' + u.path}</loc>
    <lastmod>${u.lastmod}</lastmod>
    <changefreq>${u.changefreq}</changefreq>
    <priority>${u.priority}</priority>
  </url>`
      )
      .join('\n');

    return `<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
${formattedUrls}
</urlset>`;
  };

  const currentCode = activeTab === 'robots' ? generateRobotsTxt() : generateSitemapXml();

  const handleCopy = () => {
    navigator.clipboard.writeText(currentCode);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const handleDownload = () => {
    const filename = activeTab === 'robots' ? 'robots.txt' : 'sitemap.xml';
    const blob = new Blob([currentCode], { type: 'text/plain;charset=utf-8' });
    const link = document.createElement('a');
    link.href = URL.createObjectURL(blob);
    link.download = filename;
    link.click();
  };

  const addUrl = () => {
    if (!newUrlPath) return;
    setUrls([
      ...urls,
      {
        path: newUrlPath.startsWith('/') ? newUrlPath : '/' + newUrlPath,
        priority: newUrlPriority,
        changefreq: 'weekly',
        lastmod: new Date().toISOString().split('T')[0],
      },
    ]);
    setNewUrlPath('');
  };

  return (
    <div className="space-y-6">
      {/* Header Info */}
      <div className="flex flex-col md:flex-row md:items-center justify-between gap-4 border-b border-slate-800 pb-5">
        <div>
          <div className="flex items-center gap-2 text-xs font-medium text-emerald-400">
            <span>Tasks #19, #44 & #45</span>
            <span>·</span>
            <span>Google Search Console Sitemaps API</span>
            <span>·</span>
            <span className="text-slate-400">Template-based Generation & Verification</span>
          </div>
          <h2 className="text-xl font-bold text-white mt-1">Robots.txt & XML Sitemap Architect</h2>
          <p className="text-sm text-slate-400 mt-0.5">
            Automates crawl directive rules and auto-generates validated sitemap.xml files ready for GSC API submission.
          </p>
        </div>

        <div className="flex items-center gap-3">
          <a
            href="https://developers.google.com/webmaster-tools/v1/sitemaps"
            target="_blank"
            rel="noopener noreferrer"
            className="inline-flex items-center gap-1.5 px-3 py-1.5 rounded-lg border border-slate-700 bg-slate-900 text-xs font-medium text-slate-200 hover:text-white"
          >
            <span>GSC Sitemaps API Docs</span>
            <ExternalLink className="w-3.5 h-3.5" />
          </a>
        </div>
      </div>

      {/* Tabs */}
      <div className="flex items-center gap-2 p-1.5 bg-slate-900 border border-slate-800 rounded-xl w-fit">
        <button
          onClick={() => setActiveTab('robots')}
          className={`px-4 py-1.5 text-xs font-semibold rounded-lg transition-colors ${
            activeTab === 'robots' ? 'bg-slate-800 text-emerald-400 shadow-sm' : 'text-slate-400 hover:text-slate-200'
          }`}
        >
          Robots.txt Generator (Task #45)
        </button>
        <button
          onClick={() => setActiveTab('sitemap')}
          className={`px-4 py-1.5 text-xs font-semibold rounded-lg transition-colors ${
            activeTab === 'sitemap' ? 'bg-slate-800 text-emerald-400 shadow-sm' : 'text-slate-400 hover:text-slate-200'
          }`}
        >
          XML Sitemap Builder & Submitter (Task #44)
        </button>
      </div>

      {/* Editor & Preview Layout */}
      <div className="grid grid-cols-1 lg:grid-cols-12 gap-6 items-start">
        {/* Left Config Panel */}
        <div className="lg:col-span-5 bg-slate-900/70 border border-slate-800 rounded-2xl p-5 space-y-4">
          <div className="flex items-center justify-between border-b border-slate-800 pb-3">
            <h3 className="text-sm font-semibold text-white">
              {activeTab === 'robots' ? 'Directive Directives & CMS Preset' : 'URL Index Directory'}
            </h3>
            <span className="text-xs text-emerald-400 font-mono">Live Validation</span>
          </div>

          <div className="space-y-3 text-xs">
            <div>
              <label className="block text-slate-400 mb-1">Target Client Canonical Domain</label>
              <input
                type="url"
                value={siteDomain}
                onChange={(e) => setSiteDomain(e.target.value)}
                className="w-full bg-slate-950 border border-slate-800 rounded-lg px-3 py-2 text-slate-200 focus:outline-none focus:border-emerald-500 font-mono"
              />
            </div>

            {activeTab === 'robots' ? (
              <>
                <div>
                  <label className="block text-slate-400 mb-1">CMS Engine Preset</label>
                  <select
                    value={cmsPreset}
                    onChange={(e: any) => setCmsPreset(e.target.value)}
                    className="w-full bg-slate-950 border border-slate-800 rounded-lg px-3 py-2 text-slate-200 focus:outline-none focus:border-emerald-500"
                  >
                    <option value="wordpress">WordPress (Disallow wp-admin, allow admin-ajax)</option>
                    <option value="shopify">Shopify (Disallow /admin, /orders, /cart)</option>
                    <option value="nextjs">Next.js / Headless App (Allow static routes, disallow internal API)</option>
                    <option value="custom">Custom Framework</option>
                  </select>
                </div>

                <div className="space-y-2 pt-2 border-t border-slate-800">
                  <label className="flex items-center gap-2 cursor-pointer">
                    <input
                      type="checkbox"
                      checked={allowPublic}
                      onChange={(e) => setAllowPublic(e.target.checked)}
                      className="rounded bg-slate-950 border-slate-800 text-emerald-500 focus:ring-0"
                    />
                    <span className="text-slate-300">Allow search engine bots (User-agent: *)</span>
                  </label>

                  <label className="flex items-center gap-2 cursor-pointer">
                    <input
                      type="checkbox"
                      checked={disallowAdmin}
                      onChange={(e) => setDisallowAdmin(e.target.checked)}
                      className="rounded bg-slate-950 border-slate-800 text-emerald-500 focus:ring-0"
                    />
                    <span className="text-slate-300">Disallow Admin & Backoffice URLs</span>
                  </label>

                  <label className="flex items-center gap-2 cursor-pointer">
                    <input
                      type="checkbox"
                      checked={disallowSearch}
                      onChange={(e) => setDisallowSearch(e.target.checked)}
                      className="rounded bg-slate-950 border-slate-800 text-emerald-500 focus:ring-0"
                    />
                    <span className="text-slate-300">Block internal search query parameter indexing (?s=*)</span>
                  </label>
                </div>

                <div>
                  <label className="block text-slate-400 mb-1">Additional Custom Disallow Directives</label>
                  <textarea
                    rows={4}
                    value={customRules}
                    onChange={(e) => setCustomRules(e.target.value)}
                    className="w-full bg-slate-950 border border-slate-800 rounded-lg p-2.5 text-slate-200 font-mono focus:outline-none focus:border-emerald-500 text-xs resize-none"
                  />
                </div>
              </>
            ) : (
              <>
                <div className="space-y-2">
                  <div className="flex gap-2">
                    <input
                      type="text"
                      placeholder="/products/new-feature"
                      value={newUrlPath}
                      onChange={(e) => setNewUrlPath(e.target.value)}
                      className="flex-1 bg-slate-950 border border-slate-800 rounded-lg px-2.5 py-1.5 text-slate-200 font-mono"
                    />
                    <select
                      value={newUrlPriority}
                      onChange={(e) => setNewUrlPriority(e.target.value)}
                      className="bg-slate-950 border border-slate-800 rounded-lg px-2 py-1.5 text-slate-300 font-mono"
                    >
                      <option value="1.0">1.0</option>
                      <option value="0.8">0.8</option>
                      <option value="0.7">0.7</option>
                      <option value="0.5">0.5</option>
                    </select>
                    <button
                      onClick={addUrl}
                      className="px-3 py-1.5 bg-emerald-600 hover:bg-emerald-500 text-white rounded-lg font-medium"
                    >
                      Add
                    </button>
                  </div>

                  <div className="max-h-60 overflow-y-auto space-y-1.5 pr-1">
                    {urls.map((u, i) => (
                      <div
                        key={i}
                        className="flex items-center justify-between p-2 bg-slate-950 border border-slate-800/80 rounded-lg"
                      >
                        <span className="font-mono text-slate-300 truncate max-w-[200px]">{u.path}</span>
                        <div className="flex items-center gap-2">
                          <span className="font-mono text-[11px] text-emerald-400">p: {u.priority}</span>
                          <button
                            onClick={() => setUrls(urls.filter((_, idx) => idx !== i))}
                            className="text-slate-500 hover:text-rose-400"
                          >
                            ×
                          </button>
                        </div>
                      </div>
                    ))}
                  </div>
                </div>

                <div className="p-3 bg-slate-950 border border-slate-800 rounded-xl space-y-1">
                  <div className="text-slate-300 font-medium">GSC Sitemaps API Auto-Submission</div>
                  <p className="text-[11px] text-slate-400">
                    Endpoint: <code className="text-emerald-400 font-mono">PUT /sites/{'{site}'}/sitemaps/{'{path}'}</code>
                  </p>
                </div>
              </>
            )}
          </div>
        </div>

        {/* Right Code Display */}
        <div className="lg:col-span-7 bg-slate-900 border border-slate-800 rounded-2xl overflow-hidden flex flex-col">
          <div className="flex items-center justify-between px-4 py-3 bg-slate-950/70 border-b border-slate-800">
            <div className="flex items-center gap-2">
              <FileCode className="w-4 h-4 text-emerald-400" />
              <span className="text-xs font-mono text-slate-300">
                {activeTab === 'robots' ? 'robots.txt' : 'sitemap.xml'}
              </span>
            </div>
            <div className="flex items-center gap-2">
              <button
                onClick={handleCopy}
                className="inline-flex items-center gap-1.5 px-3 py-1.5 rounded-lg bg-emerald-500/10 border border-emerald-500/30 text-emerald-400 hover:bg-emerald-500/20 text-xs font-medium transition-colors"
              >
                {copied ? <Check className="w-3.5 h-3.5" /> : <Copy className="w-3.5 h-3.5" />}
                <span>{copied ? 'Copied!' : 'Copy Code'}</span>
              </button>
              <button
                onClick={handleDownload}
                className="inline-flex items-center gap-1.5 px-3 py-1.5 rounded-lg bg-slate-800 border border-slate-700 text-slate-200 hover:text-white text-xs font-medium transition-colors"
              >
                <Download className="w-3.5 h-3.5" />
                <span>Download</span>
              </button>
            </div>
          </div>

          <div className="p-4 bg-slate-950 overflow-x-auto max-h-[460px]">
            <pre className="text-xs font-mono text-emerald-300 leading-relaxed">
              <code>{currentCode}</code>
            </pre>
          </div>

          <div className="px-4 py-3 bg-slate-950/40 border-t border-slate-800 flex items-center justify-between text-xs text-slate-400">
            <span>Dev Note from Matrix: "Auto-generate sitemap.xml & standardize robots.txt per CMS on launch"</span>
            <span className="text-emerald-400 font-mono">Compliant with Sitemaps.org Protocol</span>
          </div>
        </div>
      </div>
    </div>
  );
};
